[package]
name = "fun"
version = "0.1.0"
authors = ["Edward Kmett <ekmett@gmail.com>"]
edition = "2021"

[dependencies]
az = "1.2"
cfg-if = "1.0.0"
serde = { version = "1.0.140", features = ["derive"] }

